// scripts/gen-version.js — generates the app version at build time.
// Scheme: M.m.YYYYMMDD.X — X is 0 for the first build of the day, else HHMM (24h).
// M.m comes from package.json (bump with `npm version minor|major`); patch segment unused.
// Writes git-ignored src/version.ts + android/app/version.properties.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const VERSION_TS = path.join(ROOT, 'src/version.ts');
const PROPS = path.join(ROOT, 'android/app/version.properties');
const CODE_EPOCH = Date.UTC(2026, 0, 1);

const pad = n => String(n).padStart(2, '0');

function computeVersion(majorMinor, prevVersion, now) {
  const date = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}`;
  const prevDate = (prevVersion || '').split('.')[2];
  const time = prevDate === date ? `${pad(now.getHours())}${pad(now.getMinutes())}` : '0';
  return `${majorMinor}.${date}.${time}`;
}

// ponytail: minutes-since-epoch — two builds in the same minute share a versionCode;
// fine for adb install -r on a single-user sideload.
const versionCode = now => Math.floor((now.getTime() - CODE_EPOCH) / 60000);

function readPrev() {
  try {
    return /APP_VERSION = '([^']+)'/.exec(fs.readFileSync(VERSION_TS, 'utf8'))[1];
  } catch {
    return null;
  }
}

function main() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  const [major, minor] = pkg.version.split('.');
  const now = new Date();
  const version = computeVersion(`${major}.${minor}`, readPrev(), now);
  fs.writeFileSync(
    VERSION_TS,
    `// Generated by scripts/gen-version.js at build time. Git-ignored, do not edit.\n` +
      `export const APP_VERSION = '${version}';\n`,
  );
  fs.writeFileSync(PROPS, `VERSION_NAME=${version}\nVERSION_CODE=${versionCode(now)}\n`);
  console.log(`gen-version: ${version} (code ${versionCode(now)})`);
}

function selftest() {
  const assert = require('assert');
  const d = new Date(2026, 8, 1, 21, 5); // 2026-09-01 21:05 local
  assert.strictEqual(computeVersion('0.4', null, d), '0.4.20260901.0', 'first ever build');
  assert.strictEqual(
    computeVersion('0.4', '0.4.20260831.1408', d),
    '0.4.20260901.0',
    'first build of new day',
  );
  assert.strictEqual(
    computeVersion('0.4', '0.4.20260901.0', d),
    '0.4.20260901.2105',
    'second build same day',
  );
  const e = new Date(2026, 8, 2, 0, 9);
  assert.strictEqual(
    computeVersion('0.4', '0.4.20260902.0', e),
    '0.4.20260902.0009',
    'leading-zero HHMM',
  );
  assert.strictEqual(versionCode(new Date(Date.UTC(2026, 0, 1, 0, 2))), 2, 'code epoch');
  console.log('gen-version selftest passed');
}

if (require.main === module) {
  process.argv.includes('--selftest') ? selftest() : main();
}
