const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const GRADLE = path.join(ROOT, 'android/app/build.gradle');
const VERSION_TS = path.join(ROOT, 'src/version.ts');

function bumpGradle(text, version) {
  return text
    .replace(/versionName\s+"[^"]*"/, `versionName "${version}"`)
    .replace(/versionCode\s+(\d+)/, (_, n) => `versionCode ${Number(n) + 1}`);
}

function syncGradle(version) {
  const text = fs.readFileSync(GRADLE, 'utf8');
  fs.writeFileSync(GRADLE, bumpGradle(text, version));
}

function writeVersionTs(version) {
  fs.writeFileSync(
    VERSION_TS,
    `// Generated by scripts/sync-version.js on \`npm version\`. Do not edit by hand.\nexport const APP_VERSION = '${version}';\n`,
  );
}

function main() {
  const version = require(path.join(ROOT, 'package.json')).version;
  syncGradle(version);
  writeVersionTs(version);
  console.log(`synced version ${version} → build.gradle + src/version.ts`);
}

function selftest() {
  const assert = require('assert');
  const out = bumpGradle('        versionCode 3\n        versionName "0.3.83"', '0.4.0');
  assert.ok(out.includes('versionName "0.4.0"'), 'versionName updated');
  assert.ok(out.includes('versionCode 4'), 'versionCode incremented by 1');
  const out2 = bumpGradle('        versionCode 9\n        versionName "1.2.3"', '1.2.4');
  assert.ok(out2.includes('versionCode 10'), 'versionCode 9 → 10');
  console.log('sync-version selftest passed');
}

if (require.main === module) {
  if (process.argv.includes('--selftest')) {
    selftest();
  } else {
    main();
  }
}
